services:
  frontend:
    container_name: novaui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
