services:
  frontend:
    container_name: novaui-preprod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./.env.preprod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
