name: novaui

services:
  frontend:
    container_name: novaui-preprod
    image: novaui-preprod:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        BUILD_SCRIPT: build:preprod
    ports:
      - "3002:80"
    env_file:
      - ./.env.preprod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
