services:
  frontend:
    build:
      context: ../..
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./.env.development
    environment:
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ../..:/app
      - node_modules_cache:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

volumes:
  node_modules_cache:
